name: White Bird Engine CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up a matrix to run the following 3 configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        target: [release, release-gcc]
        include:
          - os: ubuntu-latest
            target: release
          - os: ubuntu-latest
            target: release-gcc
          # - os: windows-latest
          #   c_compiler: cl
          #   cpp_compiler: cl
        # exclude:
          # - os: windows-latest
          #   c_compiler: gcc
          # - os: windows-latest
          #   c_compiler: clang\

    steps:

    - name: Install dependencies (ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y valgrind

    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies

    - name: Checkout submodules
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        path: |
          dependencies
        key: submodules-${{ hashFiles('.gitmodules') }}

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build/${{ matrix.target }}" >> "$GITHUB_OUTPUT"

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.2
      with:
        version: 1.4.309.0
        cache: true

    - name: Setup pip dependencies
      run: pip install -r requirements.txt

    - name: Cache metadata
      id: cache-metadata
      uses: actions/cache@v4
      with:
        path: |
          build/release/metadata_cache
          build/release-gcc/metadata_cache
        key: metadata-cache

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: python build.py -t ${{ matrix.target }}

    - name: Test
      run: python ./run_tests.py -t ${{ matrix.target }}
